version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: registry.gitlab.com/pagekey/registry/boom:5.0
    volumes:
      - .env:/app/.env
      - .:/app # dev only
    ports:
      - 3000:80
      - 3001:3001
    command: [npm, run, dev] # dev only
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 5432:5432 # dev only
    # volumes:
    #   - ./var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: redis:7.2.3-alpine
    ports:
      - 6379:6379
